---
- name: Install packages using apt
  apt:
    name: 
        - tar
        - unzip
    state: present
    update_cache: no
  tags: ["packages","nordic"]

- name: Download zip to temp folder
  get_url: url={{nordic_url}} dest={{nordic_tmp}}
  tags: ["packages","intellij"]

- name: unzip to /usr/share/themes/
  unarchive:
    copy=no
    src={{nordic_tmp}}
    dest={{nordic_install_dir}}
  tags: ["packages","nordic"]

- name: add theme 
  command: gsettings set org.cinnamon.desktop.interface gtk-theme "Nordic"
  
- name: add preference 
  command: gsettings set org.cinnamon.desktop.wm.preferences theme "Nordic"
